import tkinter as tk
from tkinter import *

root = Tk()
root.geometry("444x344")
root.config(bg="gray")
root.title("Login")
frame = Frame()
login  = Label(frame,text="Login",font=("Arial",30),fg="blue",bg="gray")
l_ = Label(frame,text="username")
p_ = Entry(frame)
c_ = Label(frame,text="password")
d_ = Entry(frame,show="-")
b_ = Button(frame,text="LOGIN")
login.grid(row=1,column=1,sticky="news",padx=10,pady=20)
l_.grid(row=2,column=2,sticky="news")
p_.grid(row=2,column=3,sticky="news")
c_.grid(row=3,column=2,sticky="news")
d_.grid(row=3,column=3,sticky="news")
frame.pack()
root.mainloop()